name: Makefile CI

on: [ push, pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Run Tests
      run: make test

    - name: Install dependencies
      run: make
