name: Run Tests
on: [push, pull_request]
jobs:
  run-tests:
    name: Run OttO Tests 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Tests
        run: make test
